drop table if exists album CASCADE;
drop table if exists artist CASCADE;
drop table if exists track CASCADE;
create table album (id integer generated by default as identity, length integer, name varchar(255), year integer, artist_id integer, primary key (id));
create table artist (id integer generated by default as identity, country varchar(255), end_year integer, name varchar(255), start_year integer, primary key (id));
create table track (id integer generated by default as identity, length integer, name varchar(255), track_number integer, album_id integer, primary key (id));
alter table artist add constraint UK_r03a96lqhsb7djq2tn4rq60vn unique (name);
alter table album add constraint FKmwc4fyyxb6tfi0qba26gcf8s1 foreign key (artist_id) references artist;
alter table track add constraint FKaxm9pbgk7ptorfyk3o6911q05 foreign key (album_id) references album;